# calculate gap betwen MBM and living wage

# Create a manual mapping of your Living Wage cities to MBM regions
lookup_table <- tribble(
  ~lw_city,           ~mbm_region,
  "Brooks",          "Alberta, population under 30,000",
  "Calgary",         "Calgary, Alberta",
  "Drayton Valley", "Alberta, population under 30,000",
  "Edmonton",        "Edmonton, Alberta",
  "Fort McMurray",    "Alberta, population 30,000 to 99,999",
  "Grande Prairie",   "Alberta, population 30,000 to 99,999",
  "High River",       "Alberta, population under 30,000",
  "Jasper",       "Alberta, population under 30,000",
  "Lethbridge",      "Alberta, population 100,000 to 499,999",
  "Medicine Hat",    "Alberta, population 30,000 to 99,999",
  "Red Deer",        "Alberta, population 100,000 to 499,999",
  "Spruce Grove",    "Alberta, population 30,000 to 99,999",
  "St. Albert",      "Alberta, population 30,000 to 99,999",
  "Stony Plain",      "Alberta, population under 30,000",
  "Clayoquot Sound", "British Columbia, population under 30,000",
  "Columbia Valley", "British Columbia, population under 30,000",
  "Comox Valley",    "British Columbia, population 30,000 to 99,999",
  "Cowichan Valley", "British Columbia, population 30,000 to 99,999",
  "Daajing Giids",     "British Columbia, rural",
  "Dawson Creek",     "British Columbia, population under 30,000",
  "Fraser Valley",    "British Columbia, population 100,000 to 499,999",
  "Golden",        "British Columbia, population under 30,000",
  "Kamloops",       "British Columbia, population 100,000 to 499,999",
  "Kelowna",        "British Columbia, population 100,000 to 499,999",
  "Metro Vancouver", "Vancouver, British Columbia",
  "Nanaimo",        "British Columbia, population 100,000 to 499,999",
  "Nelson",         "British Columbia, population under 30,000",
  "Powell River",     "British Columbia, population under 30,000",
  "Prince George",   "British Columbia, population 30,000 to 99,999",
  "Revelstoke",      "British Columbia, population under 30,000",
  "Sunshine Coast",     "British Columbia, rural",
  "Trail",         "British Columbia, population under 30,000",
  "Victoria",       "British Columbia, population 100,000 to 499,999",
  "Halifax",        "Halifax, Nova Scotia",
  "Annapolis Valley", "Nova Scotia, population under 30,000",
  "Cape Breton",     "Nova Scotia, population 30,000 to 99,999",
  "Northern",       "Nova Scotia, population under 30,000",
  "Southern",      "Nova Scotia, population under 30,000",
  "Regina",        "Regina, Saskatchewan",
  "Saskatoon",      "Saskatoon, Saskatchewan",
  "Winnipeg",       "Winnipeg, Manitoba",
  "Thompson",       "Manitoba, population under 30,000",
  "Brandon",       "Brandon, Manitoba",
  "Hamilton",       "Hamilton/Burlington, Ontario",
  "East",        "Ontario, population 500,000 and over",
  "Dufferin Guelph Wellington Waterloo",  "Ontario, population 500,000 and over",
  "Brant Haldimand Norfolk Niagara",    "Ontario, population 500,000 and over",
  "London Elgin Oxford",      "Ontario, population 500,000 and over",
  "Southwest",        "Ontario, population 100,000 to 499,999",
  "Grey Bruce Perth Huron Simcoe",     "Ontario, population 100,000 to 499,999",
  "North",        "Ontario, population 100,000 to 499,999",
  # Add the rest of your matches here...
)

# mbm data is weird?? it has too many rows, not sure which value is right for each place,
# and I also need to figure out whether to use constant dollars etc