# manual mapping of Living Wage cities to MBM regions
lookup_table <- tribble(
  ~lw_region,           ~mbm_region,                               ~median_income_region,
  "Brooks",          "Alberta, population under 30,000",            "Brooks, Alberta",
  "Calgary",         "Calgary, Alberta",                            "Calgary, Alberta",
  "Drayton Valley", "Alberta, population under 30,000",             "Non CMA-CA, Alberta",
  "Edmonton",        "Edmonton, Alberta",                            "Edmonton, Alberta",
  "Fort McMurray",    "Alberta, population 30,000 to 99,999",        "Non CMA-CA, Alberta",
  "Grand Prairie",   "Alberta, population 30,000 to 99,999",       "Grande Prairie, Alberta",
  "High River",       "Alberta, population under 30,000",            "High River, Alberta",
  "Jasper",       "Alberta, population under 30,000",                 "Non CMA-CA, Alberta",
  "Lethbridge",      "Alberta, population 100,000 to 499,999",       "Lethbridge, Alberta",
  "Medicine Hat",    "Alberta, population 30,000 to 99,999",         "Medicine Hat, Alberta",
  "Red Deer",        "Alberta, population 100,000 to 499,999",       "Red Deer, Alberta",
  "Spruce Grove",    "Alberta, population 30,000 to 99,999",         "Non CMA-CA, Alberta",
  "St. Albert",      "Alberta, population 30,000 to 99,999",        "Non CMA-CA, Alberta",
  "Stony Plain",      "Alberta, population under 30,000",           "Non CMA-CA, Alberta",
  "Clayoquot Sound", "British Columbia, population under 30,000",    "Non CMA-CA, British Columbia",
  "Columbia Valley", "British Columbia, population under 30,000",    "Non CMA-CA, British Columbia",
  "Comox Valley",    "British Columbia, population 30,000 to 99,999", "Courtenay, British Columbia",
  "Cowichan Valley", "British Columbia, population 30,000 to 99,999", "Duncan, British Columbia",
  "Daajing Giids",     "British Columbia, rural",                    "Non CMA-CA, British Columbia",
  "Dawson Creek",     "British Columbia, population under 30,000",    "Dawson Creek, British Columbia",
  "Fraser Valley",    "British Columbia, population 100,000 to 499,999",  "Abbotsford-Mission, British Columbia",
  "Golden",        "British Columbia, population under 30,000",       "Non CMA-CA, British Columbia",
  "Kamloops",       "British Columbia, population 100,000 to 499,999",       "Kamloops, British Columbia",
  "Kelowna",        "British Columbia, population 100,000 to 499,999",       "Kelowna, British Columbia",
  "Metro Vancouver", "Vancouver, British Columbia",                      "Vancouver, British Columbia",
  "Nanaimo",        "British Columbia, population 100,000 to 499,999",    "Nanaimo, British Columbia",
  "Nelson",         "British Columbia, population under 30,000",      "Nelson, British Columbia",
  "Powell River",     "British Columbia, population under 30,000",    "Powell River, British Columbia",
  "Prince George",   "British Columbia, population 30,000 to 99,999",    "Prince George, British Columbia",
  "Revelstoke",      "British Columbia, population under 30,000",        "Non CMA-CA, British Columbia",
  "Sunshine Coast",     "British Columbia, rural",                      "Non CMA-CA, British Columbia",
  "Trail",         "British Columbia, population under 30,000",         "Trail, British Columbia",
  "Victoria",       "British Columbia, population 100,000 to 499,999",     "Victoria, British Columbia",
  "Halifax",        "Halifax, Nova Scotia",                              "Halifax, Nova Scotia",
  "Annapolis Valley", "Nova Scotia, population under 30,000",            "Kentville, Nova Scotia",
  "Cape Breton",     "Nova Scotia, population 30,000 to 99,999",         "Cape Breton, Nova Scotia",
  "Northern",       "Nova Scotia, population under 30,000",              "Non CMA-CA, Nova Scotia",
  "Southern",      "Nova Scotia, population under 30,000",                "Non CMA-CA, Nova Scotia",
  "Regina",        "Regina, Saskatchewan",                               "Regina, Saskachewan",
  "Saskatoon",      "Saskatoon, Saskatchewan",                           "Saskatoon, Saskatchewan",
  "Winnipeg",       "Winnipeg, Manitoba",                                "Winnipeg, Manitoba",
  "Thompson",       "Manitoba, population under 30,000",                 "Thompson, Manitoba",
  "Brandon",       "Brandon, Manitoba",                                   "Brandon, Manitoba",
  "Hamilton",       "Hamilton/Burlington, Ontario",                       "Hamilton, Ontario",
  "East",        "Ontario, population 500,000 and over",                   NA,
  "Dufferin Guelph Wellington Waterloo",  "Ontario, population 500,000 and over", "Kitchener-Cambridge-Waterloo, Ontario",
  "Brant Haldimand Norfolk Niagara",    "Ontario, population 500,000 and over",  NA,
  "London Elgin Oxford",      "Ontario, population 500,000 and over",          "London, Ontario",
  "Southwest",        "Ontario, population 100,000 to 499,999",                NA,
  "Grey Bruce Perth Huron Simcoe",     "Ontario, population 100,000 to 499,999",  NA,
  "North",        "Ontario, population 100,000 to 499,999",                     NA,
  "Ottawa",       "Ottawa-Gatineau, Ontario part, Ontario/Quebec",            "Ottawa-Gatineau, Ontario part",
  "GTA",         "Toronto, Ontario",                                         "Toronto, Ontario",
  "Whitehorse",    "Yukon, Whitehorse",                                      "Whitehorse, Yukon",
  "Montréal",        "Montréal, Québec",                                    "Montréal, Quebec",
  "Québec",            "Québec, Quebec",                                   "Québec, Quebec",
  "Gatineau",           "Quebec, population 100,000 to 499,999",            "Ottawa-Gatineau, Quebec part",
  "Sherbrooke",         "Quebec, population 100,000 to 499,999",               "Sherbrooke, Quebec",
  "Saguenay",         "Quebec, population 100,000 to 499,999",               "aguenay, Quebec",
  "Trois-Rivières", "Quebec, population 100,000 to 499,999",               "Trois-Rivières, Quebec",
  "Sept-Îles",       "Quebec, population under 30,000",                    "Sept-Îles, Quebec"
)